"""add orchestrator_runs table

Revision ID: 2c27f2427418
Revises: 3a725fa2823e
Create Date: 2026-08-08 11:29:29.622554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c27f2427418'
down_revision: Union[str, None] = '3a725fa2823e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_buying_group_account_id'), table_name='buying_group')
    op.drop_index(op.f('idx_buying_group_group_id'), table_name='buying_group')
    op.drop_table('buying_group')
    op.drop_table('Account')
    op.drop_index(op.f('idx_contact_account_id'), table_name='contact')
    op.drop_index(op.f('idx_contact_duplicate_key'), table_name='contact')
    op.drop_index(op.f('idx_contact_email'), table_name='contact')
    op.drop_index(op.f('idx_contact_owner_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('idx_consent_register_contact_id'), table_name='consent_register')
    op.drop_index(op.f('idx_consent_register_region'), table_name='consent_register')
    op.drop_index(op.f('idx_consent_register_status'), table_name='consent_register')
    op.drop_table('consent_register')
    op.drop_table('opportunity')
    op.drop_table('sequences')
    op.drop_table('sdr_roster')
    op.drop_table('icp_scoring_config')
    op.drop_table('visitor_activity')
    op.drop_table('routing_rules')
    op.drop_table('field_dictionary')
    op.drop_index(op.f('idx_enrichment_company_domain'), table_name='enrichment_data')
    op.drop_index(op.f('idx_enrichment_matched_account_id'), table_name='enrichment_data')
    op.drop_table('enrichment_data')
    op.drop_table('territories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('territories',
    sa.Column('territory_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('segment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('primary_owner_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('territory_id', name=op.f('territories_pkey'))
    )
    op.create_table('enrichment_data',
    sa.Column('enrichment_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company_domain', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('matched_account_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('revenue_band', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_range', postgresql.CIDR(), autoincrement=False, nullable=True),
    sa.Column('hq_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_competitor', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('last_verified', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('confidence >= 0::numeric AND confidence <= 1::numeric', name=op.f('enrichment_data_confidence_check')),
    sa.CheckConstraint('employees >= 0', name=op.f('enrichment_data_employees_check')),
    sa.PrimaryKeyConstraint('enrichment_id', name=op.f('enrichment_data_pkey'))
    )
    op.create_index(op.f('idx_enrichment_matched_account_id'), 'enrichment_data', ['matched_account_id'], unique=False)
    op.create_index(op.f('idx_enrichment_company_domain'), 'enrichment_data', ['company_domain'], unique=False)
    op.create_table('field_dictionary',
    sa.Column('Sheet', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Class', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('"Class" = ANY (ARRAY[\'transactional\'::text, \'master\'::text, \'config\'::text, \'reference\'::text, \'note\'::text])', name=op.f('field_dictionary_class_check')),
    sa.PrimaryKeyConstraint('Sheet', name=op.f('field_dictionary_pkey'))
    )
    op.create_table('routing_rules',
    sa.Column('rule_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('segment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('routing_rules_pkey'))
    )
    op.create_table('visitor_activity',
    sa.Column('row_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visitor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prospect_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('company_domain', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('row_id', name=op.f('visitor_activity_pkey'))
    )
    op.create_table('icp_scoring_config',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('attribute', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('icp_scoring_config_pkey'))
    )
    op.create_table('sdr_roster',
    sa.Column('owner_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('territory', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('segment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('current_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('owner_id', name=op.f('sdr_roster_pkey'))
    )
    op.create_table('sequences',
    sa.Column('sequence_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_touches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eligible_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('wait_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sequence_id', name=op.f('sequences_pkey'))
    )
    op.create_table('opportunity',
    sa.Column('Id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('AccountId', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ContactId', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('StageName', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('Probability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CloseDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('LeadSource', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('OwnerId', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('IsClosed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('IsWon', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('CreatedDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name=op.f('opportunity_pkey'))
    )
    op.create_table('consent_register',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('consent_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('basis', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('captured_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("basis = ANY (ARRAY['opt_in'::text, 'consent'::text, 'soft_opt_in'::text, 'legitimate_interest'::text])", name=op.f('consent_register_basis_check')),
    sa.CheckConstraint("status = ANY (ARRAY['active'::text, 'withdrawn'::text, 'expired'::text])", name=op.f('consent_register_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('consent_register_pkey')),
    sa.UniqueConstraint('consent_id', name=op.f('consent_register_consent_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_consent_register_status'), 'consent_register', ['status'], unique=False)
    op.create_index(op.f('idx_consent_register_region'), 'consent_register', ['region'], unique=False)
    op.create_index(op.f('idx_consent_register_contact_id'), 'consent_register', ['contact_id'], unique=False)
    op.create_table('contact',
    sa.Column('Id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('FirstName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('LastName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('AccountId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('LeadSource', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Lead_Stage__c', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('HasOptedOutOfEmail', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('DoNotCall', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('OwnerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Owner_Name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('CreatedDate', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('LastModifiedDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('LastActivityDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('consent_basis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('duplicate_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.CheckConstraint('"Lead_Stage__c" = ANY (ARRAY[\'Open\'::text, \'MQL\'::text, \'SQL\'::text, \'Opportunity\'::text, \'Customer\'::text])', name=op.f('contact_lead_stage_check')),
    sa.PrimaryKeyConstraint('Id', name=op.f('contact_pkey'))
    )
    op.create_index(op.f('idx_contact_owner_id'), 'contact', ['OwnerId'], unique=False)
    op.create_index(op.f('idx_contact_email'), 'contact', ['Email'], unique=False)
    op.create_index(op.f('idx_contact_duplicate_key'), 'contact', ['duplicate_key'], unique=False)
    op.create_index(op.f('idx_contact_account_id'), 'contact', ['AccountId'], unique=False)
    op.create_table('Account',
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('NumberOfEmployees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('BillingCountry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('OwnerId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Strategic__c', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name=op.f('Account_pkey'))
    )
    op.create_table('buying_group',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('added_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("role = ANY (ARRAY['champion'::text, 'economic_buyer'::text, 'user'::text, 'influencer'::text])", name=op.f('buying_group_role_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('buying_group_pkey')),
    sa.UniqueConstraint('group_id', 'contact_id', name=op.f('buying_group_unique_member'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_buying_group_group_id'), 'buying_group', ['group_id'], unique=False)
    op.create_index(op.f('idx_buying_group_account_id'), 'buying_group', ['account_id'], unique=False)
    # ### end Alembic commands ###
