"""add orchestrator_runs table

Revision ID: 6f961bffb365
Revises: c3d4e5f6g7h8
Create Date: 2026-08-08 05:52:20.362389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f961bffb365'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_category_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_middleware'), table_name='audit_logs')
    op.drop_column('items', 'status')
    op.drop_column('items', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_logs_is_middleware'), 'audit_logs', ['is_middleware'], unique=False)
    op.create_index(op.f('ix_audit_logs_category_timestamp'), 'audit_logs', ['category', 'timestamp'], unique=False)
    # ### end Alembic commands ###
